import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      {
        source: "/index.html",
        destination: "/",
        permanent: true,
      },
      // Silinen/birleştirilen/taşınan site kayıtlarının eski URL'leri —
      // 404 yerine yaşayan varislerine kalıcı yönlendirme (SEO değeri taşınır).
      { source: "/mahalleler/altay/ege-bloklari", destination: "/mahalleler/altay/age-bloklari", permanent: true },
      { source: "/mahalleler/altay/eryaman-doktorlar-sitesi", destination: "/mahalleler/altay/doktorlar-sitesi", permanent: true },
      { source: "/mahalleler/altay/firat-life-style", destination: "/mahalleler/altay/firat-life-style-botanik", permanent: true },
      { source: "/mahalleler/altay/frekans-cadde", destination: "/mahalleler/altay/frekans-eryaman", permanent: true },
      { source: "/mahalleler/altay/kutlutas-villalari", destination: "/mahalleler/altay/kutlutas-sitesi", permanent: true },
      { source: "/mahalleler/ata/bilgeturk-manzara-evleri", destination: "/mahalleler/ata", permanent: true },
      { source: "/mahalleler/ata/erkent-umut-sitesi", destination: "/mahalleler/ata/beloren-manzara-evleri", permanent: true },
      { source: "/mahalleler/ata/prestige-park-konutlari", destination: "/mahalleler/ata/prestij-park-konutlari", permanent: true },
      { source: "/mahalleler/ata/selvi-evleri", destination: "/mahalleler/ata/selvi-evleri-sitesi", permanent: true },
      { source: "/mahalleler/ata/sogut-bahce-sitesi", destination: "/mahalleler/ata/sogut-bahce-konutlari", permanent: true },
      { source: "/mahalleler/cumhuriyet/bati-konutlari", destination: "/mahalleler/cumhuriyet", permanent: true },
      { source: "/mahalleler/cumhuriyet/green-tower", destination: "/mahalleler/cumhuriyet/ap-green-tower", permanent: true },
      { source: "/mahalleler/cumhuriyet/kiratli-akropolis", destination: "/mahalleler/cumhuriyet", permanent: true },
      { source: "/mahalleler/cumhuriyet/tuna-park-evleri", destination: "/mahalleler/cumhuriyet", permanent: true },
      { source: "/mahalleler/cumhuriyet/yeni-botanik-parki", destination: "/mahalleler/cumhuriyet/yeni-botanik-sitesi", permanent: true },
      { source: "/mahalleler/devlet/cagrikent-sitesi", destination: "/mahalleler/devlet", permanent: true },
      { source: "/mahalleler/devlet/ornek-tes-is-sitesi", destination: "/mahalleler/devlet/tes-is-bloklari", permanent: true },
      { source: "/mahalleler/eryaman/ankapark-sitesi", destination: "/mahalleler/eryaman/ankapark-konutlari", permanent: true },
      { source: "/mahalleler/eryaman/atakent-2-sitesi", destination: "/mahalleler/eryaman/atakent-2-cumhuriyet-sitesi", permanent: true },
      { source: "/mahalleler/eryaman/gestas-toki", destination: "/mahalleler/eryaman", permanent: true },
      { source: "/mahalleler/eryaman/metrokent-sitesi", destination: "/mahalleler/eryaman", permanent: true },
      { source: "/mahalleler/eryaman/sehr-i-huzur-gold-konutlari", destination: "/mahalleler/eryaman/asm-golt-sitesi", permanent: true },
      { source: "/mahalleler/eryaman/sehr-i-huzur-prestij-konutlari", destination: "/mahalleler/eryaman/asm-prestij-konutlari", permanent: true },
      { source: "/mahalleler/goksu/alya-park", destination: "/mahalleler/susuz/alya-park", permanent: true },
      { source: "/mahalleler/goksu/bella-garden", destination: "/mahalleler/susuz/bella-garden", permanent: true },
      { source: "/mahalleler/goksu/bordo-gol-evleri", destination: "/mahalleler/susuz/bordo-gol-evleri", permanent: true },
      { source: "/mahalleler/goksu/goksu-marina", destination: "/mahalleler/susuz/goksu-marina", permanent: true },
      { source: "/mahalleler/goksu/green-life-goksu", destination: "/mahalleler/susuz/green-life-goksu-konutlari", permanent: true },
      { source: "/mahalleler/goksu/green-life-goksu-konutlari", destination: "/mahalleler/susuz/green-life-goksu-konutlari", permanent: true },
      { source: "/mahalleler/goksu/korucam-sitesi", destination: "/mahalleler/susuz/korucam-sitesi", permanent: true },
      { source: "/mahalleler/goksu/lake-life", destination: "/mahalleler/susuz/lake-life", permanent: true },
      { source: "/mahalleler/goksu/lilyum-sitesi", destination: "/mahalleler/susuz/lilyum-sitesi", permanent: true },
      { source: "/mahalleler/goksu/liva-goksu", destination: "/mahalleler/susuz/liva-goksu", permanent: true },
      { source: "/mahalleler/goksu/merdin-sitesi", destination: "/mahalleler/susuz/merdin-sitesi", permanent: true },
      { source: "/mahalleler/goksu/metrokent-sitesi", destination: "/mahalleler/goksu", permanent: true },
      { source: "/mahalleler/goksu/neovadi-konutlari", destination: "/mahalleler/susuz/neovadi-konutlari", permanent: true },
      { source: "/mahalleler/goksu/neva-palas", destination: "/mahalleler/susuz/neva-palas", permanent: true },
      { source: "/mahalleler/goksu/nil-my-home", destination: "/mahalleler/susuz/nil-my-home", permanent: true },
      { source: "/mahalleler/goksu/perla-life", destination: "/mahalleler/susuz/perla-life", permanent: true },
      { source: "/mahalleler/goksu/serline-konutlari", destination: "/mahalleler/susuz/serline-konutlari", permanent: true },
      { source: "/mahalleler/goksu/spor-sitesi", destination: "/mahalleler/goksu/gsv-spor-sitesi", permanent: true },
      { source: "/mahalleler/goksu/utku-kent-1-sitesi", destination: "/mahalleler/goksu/utku-kent-2-sitesi", permanent: true },
      { source: "/mahalleler/goksu/uzuner-sitesi", destination: "/mahalleler/altay/uzuner-konutlari", permanent: true },
      { source: "/mahalleler/goksu/vera-life-goksu", destination: "/mahalleler/susuz/vera-life-goksu", permanent: true },
      { source: "/mahalleler/goksu/white-dream-sitesi", destination: "/mahalleler/susuz/white-dream-sitesi", permanent: true },
      { source: "/mahalleler/guzelkent/ersan-sitesi", destination: "/mahalleler/guzelkent/kosk-sitesi", permanent: true },
      { source: "/mahalleler/guzelkent/eryaman-renk-villalari", destination: "/mahalleler/guzelkent/renk-villalari", permanent: true },
      { source: "/mahalleler/guzelkent/guz-gol-sitesi", destination: "/mahalleler/yavuz-selim/guz-gol-sitesi", permanent: true },
      { source: "/mahalleler/guzelkent/seniz-konut-kooperatifi", destination: "/mahalleler/guzelkent/seniz-sitesi", permanent: true },
      { source: "/mahalleler/sehit-osman-avci/akin-689-konutlari", destination: "/mahalleler/sehit-osman-avci/akin-688-konutlari", permanent: true },
      { source: "/mahalleler/sehit-osman-avci/armonia-konutlari", destination: "/mahalleler/sehit-osman-avci/alpak-neve-armonia-residence", permanent: true },
      { source: "/mahalleler/sehit-osman-avci/firat-life-style-goksu-sitesi", destination: "/mahalleler/sehit-osman-avci/goksu-prestij", permanent: true },
      { source: "/mahalleler/sehit-osman-avci/golde-luxe-konutlari", destination: "/mahalleler/cumhuriyet/golde-luxe-konutlari", permanent: true },
      { source: "/mahalleler/sehit-osman-avci/hill-tower-cadde", destination: "/mahalleler/sehit-osman-avci/hill-tower-goksu", permanent: true },
      { source: "/mahalleler/sehit-osman-avci/koroglu-goldekent-evleri", destination: "/mahalleler/sehit-osman-avci/goldekent-sitesi", permanent: true },
      { source: "/mahalleler/seyh-samil/concept-eryaman", destination: "/mahalleler/yavuz-selim/concept-eryaman", permanent: true },
      { source: "/mahalleler/seyh-samil/alarko-sitesi", destination: "/mahalleler/seyh-samil/alarko-bloklari", permanent: true },
      { source: "/mahalleler/seyh-samil/alkon-sitesi", destination: "/mahalleler/ata/alkon-sitesi", permanent: true },
      { source: "/mahalleler/seyh-samil/borankent-sitesi", destination: "/mahalleler/seyh-samil/borankent", permanent: true },
      { source: "/mahalleler/seyh-samil/dilara-sitesi", destination: "/mahalleler/ata/dilara-sitesi", permanent: true },
      { source: "/mahalleler/seyh-samil/eston-2-sitesi", destination: "/mahalleler/seyh-samil/eston-bloklari", permanent: true },
      { source: "/mahalleler/seyh-samil/hava-yollari-sitesi", destination: "/mahalleler/yavuz-selim/havayollari-sitesi", permanent: true },
      { source: "/mahalleler/seyh-samil/oz-ahi-sitesi", destination: "/mahalleler/seyh-samil/ozahikent-sitesi", permanent: true },
      { source: "/mahalleler/seyh-samil/ozahi-kent", destination: "/mahalleler/seyh-samil/ozahikent-sitesi", permanent: true },
      { source: "/mahalleler/seyh-samil/rusen-park-sitesi", destination: "/mahalleler/ata/rusen-park-evleri", permanent: true },
      { source: "/mahalleler/seyh-samil/vizyon-baspinar", destination: "/mahalleler/ata/vizyon-baspinar-sitesi", permanent: true },
      { source: "/mahalleler/susuz/mizan-sitesi", destination: "/mahalleler/ata/mizan-sitesi", permanent: true },
      { source: "/mahalleler/susuz/ozkardesler-sitesi", destination: "/mahalleler/ata/ozkardesler-sitesi", permanent: true },
      { source: "/mahalleler/susuz/palmiye-evleri", destination: "/mahalleler/susuz/tatli-yamac-palmiye-evleri", permanent: true },
      { source: "/mahalleler/susuz/panorama-gold", destination: "/mahalleler/ata/panorama-gold", permanent: true },
      { source: "/mahalleler/susuz/paradise-goksu-konutlari", destination: "/mahalleler/susuz/paradise-goksu", permanent: true },
      { source: "/mahalleler/susuz/rusen-park-evleri", destination: "/mahalleler/ata/rusen-park-evleri", permanent: true },
      { source: "/mahalleler/susuz/ruya-kent-sitesi", destination: "/mahalleler/ata/ruyakent-sitesi", permanent: true },
      { source: "/mahalleler/susuz/sumeyra-2-sitesi", destination: "/mahalleler/ata/sumeyra-2-sitesi", permanent: true },
      { source: "/mahalleler/susuz/vizyon-baspinar-sitesi", destination: "/mahalleler/ata/vizyon-baspinar-sitesi", permanent: true },
      { source: "/mahalleler/tunahan/kur-sitesi", destination: "/mahalleler/tunahan/kur-sitesi-46495-ada", permanent: true },
      { source: "/mahalleler/tunahan/kur-sitesi-c1b-2k", destination: "/mahalleler/tunahan/kur-sitesi-46495-ada", permanent: true },
      { source: "/mahalleler/tunahan/kur-sitesi-c2b-2h", destination: "/mahalleler/tunahan/kur-sitesi-46496-ada", permanent: true },
      { source: "/mahalleler/yavuz-selim/aker-mucevher-evleri", destination: "/mahalleler/ata/aker-mucevher-evleri", permanent: true },
      { source: "/mahalleler/yavuz-selim/demirglass-sitesi", destination: "/mahalleler/seyh-samil/lider-yasam-evleri", permanent: true },
      { source: "/mahalleler/yavuz-selim/elitnar-cicegi-sitesi", destination: "/mahalleler/yavuz-selim/elit-nar-cicegi", permanent: true },
      { source: "/mahalleler/yavuz-selim/genova", destination: "/mahalleler/ata/genova", permanent: true },
      { source: "/mahalleler/yavuz-selim/gold-life-konutlari", destination: "/mahalleler/ata/gold-life-konutlari", permanent: true },
      { source: "/mahalleler/yavuz-selim/mavi-bayrak-sitesi", destination: "/mahalleler/ata/mavi-bayrak-sitesi", permanent: true },
      { source: "/mahalleler/yavuz-selim/ozahikent-sitesi", destination: "/mahalleler/seyh-samil/ozahikent-sitesi", permanent: true },
      { source: "/mahalleler/yavuz-selim/panorama-plus", destination: "/mahalleler/ata/panorama-plus", permanent: true },
      { source: "/mahalleler/yavuz-selim/prestige-park-konutlari", destination: "/mahalleler/ata/prestij-park-konutlari", permanent: true },
      { source: "/mahalleler/yavuz-selim/selvi-evleri", destination: "/mahalleler/ata/selvi-evleri-sitesi", permanent: true },
      { source: "/mahalleler/yesilova/doganlife-yesilova", destination: "/mahalleler/yesilova/dogan-life", permanent: true },
      { source: "/mahalleler/yesilova/ekiciler-sitesi", destination: "/mahalleler/yesilova", permanent: true },
      { source: "/mahalleler/yesilova/meric-sitesi", destination: "/mahalleler/yesilova", permanent: true },
    ];
  },
};

export default nextConfig;
